### ISSUE TITLE
Dump internal docs

### ISSUE THREAD

**Issue by Frostbyte0x70** [End45/pmdsky-debug#1]
Current progress at dumping my ASM notes, divided in sections:

- [x] Structs and enums
- [x] Moves and damage
- [x] Reviving
- [x] Message printing
- [x] Fainting
- [x] Types and effectiveness
- [x] Dungeon mode cycle
- [x] AI
- [x] Move animations
- [x] Dungeon mode menus
- [x] Main menu and submenus
- [x] Pokémon list submenu
- [x] Items submenu
- [x] Missions
- [x] Leader changing
- [x] Floors
- [x] Starter pokémon selection
- [x] Move selection menu
- [x] Team menu
- [x] Dungeon camera
- [x] Enemy spawn check
- [x] Enemy spawning
- [x] Belly
- [x] PP
- [x] IQ
- [x] Recruiting
- [x] Moves and effects
- [x] Minimap
- [x] RNG
- [x] Stepping on items / traps
- [x] Invisibility
- [x] Natural HP regeneration
- [x] Player input
- [x] Dungeon init
- [x] Exclusive item effects
- [x] Exclusive item swapping
- [x] Quicksaving
- [x] Dungeon grid
- [x] Moving pokémon
- [x] Dungeon tiles
- [x] Dungeon results screen
- [x] Fixed rooms
- [x] Map markers
- [x] Save file
- [x] Clear marks
- [x] Item spawn lists
- [x] Monster initialization
- [x] Explorer rank
- [x] Fixed room checks
- [x] Bag and items
- [x] Weather graphical effects
- [x] Picking up items
- [x] Dungeon music
- [x] Overlay loading
- [x] Scripting
- [x] EXP
- [x] Sky Jukebox & Music
- [x] Hardware interrupts
- [x] Mobility
- [x] Item hurling
- [x] Anticipation
- [x] Dungeon struct
- [x] Threading
- [x] Misc
- [x] Map generation

Notes to keep in mind:

- There might be functions related to the sections listed as complete that might have not been dumped yet, since sometimes the same function is used in multiple sections, and I will only dump a function when I get to the point in my notes where it's defined, which might not be the most appropriate section for it.
- More sections might be added if I research a new field before I'm done with the whole list.
- Sections could be removed if I realize that all the functions in a section have already been dumped.

**Comment by Frostbyte0x70** [comment]
Finally, inner peace.

**Comment by UsernameFodder** [comment]
This is deeply satisfying 😄
